notifications:
  email: false
dist: trusty
language: python
python:
- '2.7'
- '3.3'
- '3.4'
branches:
  only:
  - master
before_install:
- sudo apt-get -qq update
- sudo apt-get install golang
install:
- pip install -r requirements.txt
- wget https://github.com/google/protobuf/releases/download/v3.4.0/protoc-3.4.0-linux-x86_64.zip
- unzip protoc-3.4.0-linux-x86_64.zip
- export PATH="${TRAVIS_BUILD_DIR}/bin:$PATH"
- wget http://releases.llvm.org/5.0.1/clang+llvm-5.0.1-x86_64-linux-gnu-ubuntu-14.04.tar.xz
- tar -xJf clang+llvm-5.0.1-x86_64-linux-gnu-ubuntu-14.04.tar.xz
- export PATH="${TRAVIS_BUILD_DIR}/clang+llvm-5.0.1-x86_64-linux-gnu-ubuntu-14.04/bin:$PATH"
- go get -u github.com/golang/protobuf/protoc-gen-go
script:
- make lint
- make test
- make gen
- make gen-dbc
before_deploy:
- zip codegen-tooling-out.zip out/*
deploy:
  provider: releases
  api_key:
    secure: Ab80ZULDufteUaESTN79Yh8O0wO6lplf4GcjhryOTTCQLfXsdfQozU02gHETfr3WI/UJyzjQw/XcGOkQNE6rkQsmky5YSh7bHcYJU0cvUJeQVRsP7SUPTLxlBK9+DvimU+aC/7AgTGJB+diNXdvcijmXQR6GSFbTmYMqpWGQqCORqPpFPiexOvX3X76Qc4HmI4cBz9W7Y//vTfUaApx5BF/H1V0AYnv2mReyYcydbLopUgYhphhIrbQ3WSZMuJsnSg1uuBf9GnFhOB+APNnB634fSUsq0zgn+Bdlj1lWLHgf+BMSEnbO6b/8KbvJZ7lu34aNQHpVJ0myEobdEv+n9k/Tio1K2eZMJwwnxFscwsP0vxb+thMAn+LtOA5uJQUzgY/t3gFduVuUXMwlb5VAcvwwriBt/wktwL/vA9XZMbOWfixnuWN6VumOkaGCtbVamidvtnt0CfqpazrJYxK62Uty0wRT6IYJRahI7fP5whv8VvTXMiD+4djYz2S0Xw1pwhiKdRcJcgofj9QCsITyGmitHLUfGWTxOE1olWZsBDbevcwEfqAqrH/SlbJ3tw7zQZTmFgA+OsHoVekCK3kSFZwUHQ/4WW18DDaqnETYeOJjEwpv+nZhXsgABwP8Qq/7NZB9DfphGatZZtwpX73fOn+ERnfyqaE4EmtISjor+x4=
  file: 
    - codegen-tooling-out.zip
    - system_can.dbc
  on:
    repo: taipingli/codegen-tooling
  skip_cleanup: true
